services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: ["/app/scripts/watch.sh"]
    tty: true
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./test
        - action: rebuild
          path: ./CMakeLists.txt
        - action: rebuild
          path: ./CMakePresets.json

