# import gzip
import sys

def file_to_gzip_header(input_filename: str, output_header: str, array_name: str = "CompressedData"):
    # read whole text file

    with open(input_filename, 'rb') as f:
        data = f.read()

    cpp_array = ', '.join(f'0x{byte:02X}' for byte in data)
    cpp_code = f"""#pragma once
#include <string_view>

/* THIS FILE IS AUTOGENERATED. DO NOT MODIFY. */
constexpr std::string_view {array_name}_STR = R"({data.decode('utf-8')})";
"""

    # Write to output header file
    with open(output_header, 'w') as f:
        f.write(cpp_code)

    print(f"Generated C++ header file: {output_header}")
    print(f"Array size: {len(data)} bytes")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_file> <output_header>")
        sys.exit(1)

    print(f"Input file: {sys.argv[1]}")
    print(f"Output header: {sys.argv[2]}")

    file_to_gzip_header(sys.argv[1], sys.argv[2], "TAILWIND_DATA")

